import type { InterviewSession, User } from "./types";
import { formatDate } from "./utils";

/**
 * Client-side PDF export via jsPDF.
 * Dynamically imported to keep the main bundle lean.
 */
export async function exportSessionReport(
  session: InterviewSession,
  user: User | null
): Promise<void> {
  const { default: jsPDF } = await import("jspdf");
  await import("jspdf-autotable");

  const doc = new jsPDF();
  const margin = 14;
  let y = 20;

  // Header
  doc.setFillColor(67, 56, 202);
  doc.rect(0, 0, 210, 36, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text("InterviewForge Report", margin, 18);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("AI-Powered Interview Coaching Summary", margin, 28);

  y = 48;
  doc.setTextColor(30, 30, 40);
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("Session Overview", margin, y);
  y += 8;
  doc.setFont("helvetica", "normal");
  doc.setFontSize(10);

  const lines = [
    `Candidate: ${user?.name ?? "Candidate"}`,
    `Role: ${session.role}`,
    `Mode: ${session.mode}${session.companyStyle ? ` (${session.companyStyle})` : ""}`,
    `Date: ${session.completedAt ? formatDate(session.completedAt) : formatDate(session.startedAt)}`,
    `Overall Score: ${session.overallScore?.toFixed(1) ?? "N/A"} / 10`,
    `Questions Answered: ${session.answers.length}`,
  ];
  lines.forEach((line) => {
    doc.text(line, margin, y);
    y += 6;
  });

  y += 6;
  doc.setFont("helvetica", "bold");
  doc.setFontSize(12);
  doc.text("Question Breakdown", margin, y);
  y += 4;

  const tableBody = session.answers.map((a, i) => [
    String(i + 1),
    a.questionText.slice(0, 60) + (a.questionText.length > 60 ? "…" : ""),
    a.feedback.scores.overall.toFixed(1),
    a.feedback.summary.slice(0, 50) + (a.feedback.summary.length > 50 ? "…" : ""),
  ]);

  (doc as unknown as { autoTable: (opts: Record<string, unknown>) => void }).autoTable({
    startY: y,
    head: [["#", "Question", "Score", "Summary"]],
    body: tableBody,
    theme: "striped",
    headStyles: { fillColor: [79, 70, 229] },
    margin: { left: margin, right: margin },
    styles: { fontSize: 8, cellPadding: 2 },
    columnStyles: {
      0: { cellWidth: 10 },
      1: { cellWidth: 80 },
      2: { cellWidth: 18 },
      3: { cellWidth: 70 },
    },
  });

  y =
    ((doc as unknown as { lastAutoTable?: { finalY?: number } }).lastAutoTable
      ?.finalY ?? y) + 12;

  session.answers.slice(0, 5).forEach((a, idx) => {
    if (y > 250) {
      doc.addPage();
      y = 20;
    }
    doc.setFont("helvetica", "bold");
    doc.setFontSize(11);
    doc.setTextColor(67, 56, 202);
    doc.text(`Q${idx + 1}: Feedback Detail`, margin, y);
    y += 6;
    doc.setTextColor(30, 30, 40);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(9);

    const strengths = `Strengths: ${a.feedback.strengths.join("; ")}`;
    const improvements = `Improvements: ${a.feedback.improvements.join("; ")}`;
    const wrappedS = doc.splitTextToSize(strengths, 180);
    const wrappedI = doc.splitTextToSize(improvements, 180);
    doc.text(wrappedS, margin, y);
    y += wrappedS.length * 4 + 2;
    doc.text(wrappedI, margin, y);
    y += wrappedI.length * 4 + 8;
  });

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(140);
    doc.text(
      `Generated by InterviewForge · Page ${i} of ${pageCount}`,
      margin,
      290
    );
  }

  const safeRole = session.role.replace(/[^a-z0-9]+/gi, "-").toLowerCase();
  doc.save(`interviewforge-${safeRole}-${session.id.slice(0, 8)}.pdf`);
}
