import type { InterviewQuestion } from "./types";

/**
 * Extended psychologist-informed question bank.
 * Competency-based & structured-interview items merged into QUESTIONS.
 */

function qx(
  id: string,
  text: string,
  category: InterviewQuestion["category"],
  difficulty: InterviewQuestion["difficulty"],
  opts: Partial<InterviewQuestion> = {}
): InterviewQuestion {
  return {
    id,
    text,
    category,
    mode: opts.mode ?? "all",
    roles: opts.roles ?? ["all"],
    difficulty,
    companyStyle: opts.companyStyle,
    tips: opts.tips,
    sampleAnswerOutline: opts.sampleAnswerOutline,
  };
}

export const EXTRA_QUESTIONS: InterviewQuestion[] = [
  qx("pb001", "Describe a time you changed your mind after receiving new information.", "behavioral", "medium", { mode: "behavioral", tips: "Show intellectual humility and how evidence updated your view." }),
  qx("pb002", "Tell me about a time you had to deliver difficult feedback.", "behavioral", "hard", { mode: "behavioral", tips: "Focus on care and clarity: behavior, impact, path forward." }),
  qx("pb003", "Describe a situation where you managed ambiguity with little direction.", "behavioral", "hard", { mode: "behavioral", tips: "Highlight sense-making: hypotheses, small experiments, communication." }),
  qx("pb004", "Tell me about a time you advocated for someone else.", "behavioral", "medium", { mode: "behavioral", tips: "Allyship and fairness without self-aggrandizing." }),
  qx("pb005", "Describe a time you balanced speed and quality under pressure.", "behavioral", "medium", { mode: "behavioral", tips: "Name the trade-off explicitly and the risk you accepted." }),
  qx("pb006", "Tell me about a time you recovered from a public mistake.", "behavioral", "hard", { mode: "behavioral", tips: "Ownership first; then repair and systems change." }),
  qx("pb007", "Describe when you had to say no to a stakeholder.", "behavioral", "medium", { mode: "behavioral", tips: "Protect constraints while offering alternatives." }),
  qx("pb008", "Tell me about a time you built trust with a skeptical colleague.", "behavioral", "medium", { mode: "behavioral", tips: "Consistency, small deliveries, listening." }),
  qx("pb009", "Describe a time you adapted your communication style for your audience.", "behavioral", "easy", { mode: "behavioral", tips: "Audience analysis is a core professional skill." }),
  qx("pb010", "Tell me about a goal you set that required sustained effort over months.", "behavioral", "medium", { mode: "behavioral", tips: "Grit plus systems (habits, metrics), not just motivation." }),
  qx("pb011", "Describe a time you handled competing priorities from two managers.", "behavioral", "hard", { mode: "behavioral", tips: "Negotiation and transparent prioritization." }),
  qx("pb012", "Tell me about a time you learned from someone more junior than you.", "behavioral", "easy", { mode: "behavioral", tips: "Status-free learning signals growth mindset." }),
  qx("pb013", "Describe a conflict you resolved without authority.", "behavioral", "hard", { mode: "behavioral", tips: "Influence without power; interests over positions." }),
  qx("pb014", "Tell me about a time you improved a process nobody asked you to fix.", "behavioral", "medium", { mode: "behavioral", tips: "Proactive ownership with measured impact." }),
  qx("pb015", "Describe when you had to work with incomplete data.", "behavioral", "medium", { mode: "behavioral", tips: "Decision under uncertainty; what you monitored after." }),
  qx("pb016", "Tell me about a time you supported a teammate through stress or burnout.", "behavioral", "hard", { mode: "behavioral", tips: "Psychological safety and boundaries; avoid oversharing others." }),
  qx("pb017", "Describe a time you received recognition that belonged to the team.", "behavioral", "easy", { mode: "behavioral", tips: "Redirect credit; culture of fairness." }),
  qx("pb018", "Tell me about a time you challenged a popular idea.", "behavioral", "hard", { mode: "behavioral", tips: "Courage, data, and respect; outcome matters." }),
  qx("pb019", "Describe when you rebuilt confidence after a setback.", "behavioral", "medium", { mode: "behavioral", tips: "Self-regulation and recovery strategies." }),
  qx("pb020", "Tell me about a time you managed up effectively.", "behavioral", "medium", { mode: "behavioral", tips: "Anticipating needs, concise updates, options." }),
  qx("pb021", "Describe a time you handled an ethical gray area.", "behavioral", "hard", { mode: "behavioral", tips: "Principles, stakeholders, and the decision you made." }),
  qx("pb022", "Tell me about a time you turned a critic into a collaborator.", "behavioral", "hard", { mode: "behavioral", tips: "Perspective-taking and joint problem-solving." }),
  qx("pb023", "Describe when you had to unlearn a habit that was holding you back.", "behavioral", "medium", { mode: "behavioral", tips: "Self-awareness and deliberate practice." }),
  qx("pb024", "Tell me about a time you prepared thoroughly and still had to improvise.", "behavioral", "medium", { mode: "behavioral", tips: "Flexibility without abandoning structure." }),
  qx("pb025", "Describe a time you set boundaries at work.", "behavioral", "medium", { mode: "behavioral", tips: "Sustainable performance, not avoidance." }),
  qx("pb026", "Tell me about a time you celebrated someone else's success.", "behavioral", "easy", { mode: "behavioral", tips: "Team climate and secure self-concept." }),
  qx("pb027", "Describe when you had to motivate yourself without external recognition.", "behavioral", "medium", { mode: "behavioral", tips: "Intrinsic motivation and personal standards." }),
  qx("pb028", "Tell me about a time you managed a high-stakes conversation.", "behavioral", "hard", { mode: "behavioral", tips: "Preparation, emotional regulation, clear ask." }),
  qx("pb029", "Describe a time you used data to change a narrative.", "behavioral", "medium", { mode: "behavioral", tips: "Story plus evidence; avoid data-dumping." }),
  qx("pb030", "Tell me about a time you helped a team recover after a failure.", "behavioral", "hard", { mode: "behavioral", tips: "Blameless learning energy; forward path." }),
  qx("pb031", "Describe when you prioritized learning over short-term delivery.", "behavioral", "medium", { mode: "behavioral", tips: "Investment thesis and how you justified it." }),
  qx("pb032", "Tell me about a time you noticed a bias in your own decision-making.", "behavioral", "hard", { mode: "behavioral", tips: "Metacognition; what you changed." }),
  qx("pb033", "Describe a time you onboarded yourself into a complex domain quickly.", "behavioral", "medium", { mode: "behavioral", tips: "Learning strategy: experts, docs, feedback loops." }),
  qx("pb034", "Tell me about a time you had to represent your team externally.", "behavioral", "easy", { mode: "behavioral", tips: "Clarity, confidence, and accurate representation." }),
  qx("pb035", "Describe when you disagreed with a peer in a public forum.", "behavioral", "hard", { mode: "behavioral", tips: "Disagree and commit; protect relationship." }),
  qx("pb036", "Tell me about a time you improved how your team gives feedback.", "behavioral", "medium", { mode: "behavioral", tips: "Process and psychological safety." }),
  qx("pb037", "Describe a time you handled customer or user anger.", "behavioral", "medium", { mode: "behavioral", tips: "De-escalate, validate, solve, follow up." }),
  qx("pb038", "Tell me about a time you worked across cultures or time zones.", "behavioral", "medium", { mode: "behavioral", tips: "Inclusion, async norms, assumption-checking." }),
  qx("pb039", "Describe when you chose team integrity over personal loyalty.", "behavioral", "hard", { mode: "behavioral", tips: "Values hierarchy; transparent reasoning." }),
  qx("pb040", "Tell me about a time you made a decision that was unpopular but right.", "behavioral", "hard", { mode: "behavioral", tips: "Courage, communication, results." }),
  qx("pb041", "Describe a time you coached someone through a skill gap.", "behavioral", "medium", { mode: "behavioral", tips: "Scaffolding, practice, feedback." }),
  qx("pb042", "Tell me about a time you managed your energy during a crunch period.", "behavioral", "easy", { mode: "behavioral", tips: "Recovery is part of performance." }),
  qx("pb043", "Describe when you had to reverse a decision you championed.", "behavioral", "hard", { mode: "behavioral", tips: "Ego strength and learning velocity." }),
  qx("pb044", "Tell me about a time you created alignment without a formal meeting.", "behavioral", "medium", { mode: "behavioral", tips: "Async influence and stakeholder maps." }),
  qx("pb045", "Describe a time you handled confidential information carefully.", "behavioral", "medium", { mode: "behavioral", tips: "Trust and professionalism." }),
  qx("pb046", "Tell me about a time you used storytelling to persuade.", "behavioral", "medium", { mode: "behavioral", tips: "Narrative structure plus proof points." }),
  qx("pb047", "Describe when you had to perform under evaluation or observation.", "behavioral", "medium", { mode: "behavioral", tips: "Performance anxiety coping and preparation." }),
  qx("pb048", "Tell me about a time you integrated feedback you initially resisted.", "behavioral", "hard", { mode: "behavioral", tips: "Defensiveness to curiosity pipeline." }),
  qx("pb049", "Describe a time you helped reduce team anxiety during change.", "behavioral", "hard", { mode: "behavioral", tips: "Change leadership and transparent communication." }),
  qx("pb050", "Tell me about a time you set a standard that raised team quality.", "behavioral", "medium", { mode: "behavioral", tips: "Modeling and reinforcement." }),
  qx("pb051", "Describe when you triaged emotional and technical issues at once.", "behavioral", "hard", { mode: "behavioral", tips: "Dual awareness; address people then problem." }),
  qx("pb052", "Tell me about a time you built a relationship before you needed a favor.", "behavioral", "easy", { mode: "behavioral", tips: "Relationship capital, not transactional networking." }),
  qx("pb053", "Describe a time you simplified a complex explanation for a non-expert.", "behavioral", "easy", { mode: "behavioral", tips: "Teach-back and analogies." }),
  qx("pb054", "Tell me about a time you owned an outcome you did not fully control.", "behavioral", "hard", { mode: "behavioral", tips: "Accountability with influence maps." }),
  qx("pb055", "Describe when you stayed calm while others escalated.", "behavioral", "medium", { mode: "behavioral", tips: "Emotional contagion and co-regulation." }),
  qx("pb056", "Tell me about a time you improved inclusion in a meeting or process.", "behavioral", "medium", { mode: "behavioral", tips: "Concrete behavior change, not slogans." }),
  qx("pb057", "Describe a time you closed the loop after a commitment slipped.", "behavioral", "easy", { mode: "behavioral", tips: "Reliability repair protocol." }),
  qx("pb058", "Tell me about a time you used a retrospective to change behavior.", "behavioral", "medium", { mode: "behavioral", tips: "Learning systems, not venting sessions." }),
  qx("pb059", "Describe when you chose depth over breadth of work.", "behavioral", "medium", { mode: "behavioral", tips: "Strategic focus." }),
  qx("pb060", "Tell me about a time you mentored across a difference in style or background.", "behavioral", "medium", { mode: "behavioral", tips: "Perspective-taking and tailored coaching." }),
  qx("ps001", "A peer takes credit for your work in a meeting. What do you do?", "situational", "medium", { mode: "behavioral", tips: "Address privately first; focus on facts and future credit norms." }),
  qx("ps002", "Your manager asks you to ship something you believe is unsafe. How do you respond?", "situational", "hard", { mode: "behavioral", tips: "Escalate with risk framing and alternatives; document." }),
  qx("ps003", "Two stakeholders give you opposite priorities. How do you decide?", "situational", "medium", { mode: "behavioral", tips: "Clarify success metrics, escalate trade-offs, communicate decision." }),
  qx("ps004", "A teammate is missing deadlines and seems overwhelmed. What's your approach?", "situational", "medium", { mode: "behavioral", tips: "Curiosity before judgment; support plus accountability." }),
  qx("ps005", "You discover a bug in production that you introduced. Walk me through your first hour.", "situational", "easy", { mode: "behavioral", tips: "Stabilize, communicate, fix, prevent." }),
  qx("ps006", "A customer threatens to churn over a delay you didn't cause. How do you handle it?", "situational", "hard", { mode: "behavioral", tips: "Own the relationship; options, empathy, plan." }),
  qx("ps007", "You're asked to estimate a project with huge uncertainty. What do you say?", "situational", "medium", { mode: "behavioral", tips: "Ranges, assumptions, risks, re-estimate triggers." }),
  qx("ps008", "A meeting is going off the rails. How do you intervene?", "situational", "easy", { mode: "behavioral", tips: "Facilitation: goal, parking lot, next steps." }),
  qx("ps009", "You disagree with the technical direction but the team has decided. What next?", "situational", "medium", { mode: "behavioral", tips: "Disagree and commit; earn right to revisit with data." }),
  qx("ps010", "You notice exclusionary language in a code review or doc. What do you do?", "situational", "medium", { mode: "behavioral", tips: "Direct, kind correction; model inclusive norms." }),
  qx("ps011", "Leadership wants a hero metric that you think is gameable. How do you respond?", "situational", "hard", { mode: "behavioral", tips: "Second-order effects; propose balanced metrics." }),
  qx("ps012", "You're the only one who knows a critical system and you're going on PTO. Plan?", "situational", "easy", { mode: "behavioral", tips: "Documentation, buddy, runbooks, risk register." }),
  qx("ps013", "A recruiter asks you to badmouth a former employer. How do you answer?", "situational", "easy", { mode: "behavioral", tips: "Professional boundaries; lessons without blame." }),
  qx("ps014", "Your idea fails after launch. How do you present results to leadership?", "situational", "medium", { mode: "behavioral", tips: "Outcome honesty, learning, next experiment." }),
  qx("ps015", "Someone on your team is quietly underperforming. Day-one plan?", "situational", "hard", { mode: "behavioral", tips: "Private conversation, clarity, support, timeline." }),
  qx("ps016", "You're given an impossible deadline. What do you do in the first 24 hours?", "situational", "medium", { mode: "behavioral", tips: "Scope negotiation, risk, phased delivery." }),
  qx("ps017", "A junior asks you a question you don't know. How do you handle it?", "situational", "easy", { mode: "behavioral", tips: "Model learning: look it up together, no bluffing." }),
  qx("ps018", "You overhear gossip that could harm a teammate. Response?", "situational", "medium", { mode: "behavioral", tips: "Don't amplify; redirect to constructive channels if needed." }),
  qx("ps019", "Security reports a vulnerability in your feature. Prioritization approach?", "situational", "medium", { mode: "behavioral", tips: "Severity, exploitability, user impact, fix path." }),
  qx("ps020", "Two team members refuse to work together. Your move?", "situational", "hard", { mode: "behavioral", tips: "Mediate interests; set behavioral expectations." }),
  qx("ps021", "You're asked to present without enough prep time. Strategy?", "situational", "easy", { mode: "behavioral", tips: "Structure over polish: problem, options, ask." }),
  qx("ps022", "A stakeholder rewrites your requirements mid-sprint. How do you protect delivery?", "situational", "medium", { mode: "behavioral", tips: "Change control, impact analysis, renegotiate scope." }),
  qx("ps023", "You suspect burnout in yourself. What do you do?", "situational", "medium", { mode: "behavioral", tips: "Self-awareness, support systems, sustainable plan." }),
  qx("ps024", "An AI tool produces a confident wrong answer in your work. How do you catch it?", "situational", "medium", { mode: "behavioral", tips: "Verification habits and human judgment." }),
  qx("ps025", "You're the new person and something feels off culturally. How do you investigate?", "situational", "medium", { mode: "behavioral", tips: "Observe, ask open questions, avoid early judgment." }),
  qx("ps026", "A demo fails live. Recovery script?", "situational", "easy", { mode: "behavioral", tips: "Acknowledge, diagnose, fallback, follow-up." }),
  qx("ps027", "You're offered a shortcut that violates policy slightly. Decision framework?", "situational", "hard", { mode: "behavioral", tips: "Ethics over expedience; escalate if needed." }),
  qx("ps028", "Your team is celebrating but you see a risk. How do you raise it?", "situational", "medium", { mode: "behavioral", tips: "Timing and framing: protect success by addressing risk." }),
  qx("ps029", "A user reports accessibility barriers. How do you respond?", "situational", "medium", { mode: "behavioral", tips: "Urgency, inclusion, concrete remediation." }),
  qx("ps030", "You must choose who gets limited resources. Criteria?", "situational", "hard", { mode: "behavioral", tips: "Transparent criteria, fairness, impact." }),
  qx("ps031", "A peer is consistently late to meetings. Address it how?", "situational", "easy", { mode: "behavioral", tips: "Private, specific, impact, ask for commitment." }),
  qx("ps032", "You're asked to work a weekend again. Boundary strategy?", "situational", "medium", { mode: "behavioral", tips: "Sustainable yes or no with trade-offs." }),
  qx("ps033", "A project is green on status but red in reality. What do you report?", "situational", "hard", { mode: "behavioral", tips: "Truth over comfort; early warning is leadership." }),
  qx("ps034", "Someone takes a joke too far in standup. What do you do?", "situational", "medium", { mode: "behavioral", tips: "Interrupt harm, restate norms, follow up." }),
  qx("ps035", "You inherit messy code before a deadline. Approach?", "situational", "medium", { mode: "behavioral", tips: "Stabilize, smallest safe changes, plan cleanup." }),
  qx("ps036", "A mentor gives advice that conflicts with your values. Response?", "situational", "medium", { mode: "behavioral", tips: "Integrate selectively; own your principles." }),
  qx("ps037", "You're evaluated on a metric you disagree with. How do you still succeed?", "situational", "hard", { mode: "behavioral", tips: "Deliver on shared goals while influencing metrics." }),
  qx("ps038", "A stakeholder wants daily updates that waste time. Redesign the cadence?", "situational", "easy", { mode: "behavioral", tips: "Propose async update format with value." }),
  qx("ps039", "You find a critical dependency on one person. Risk plan?", "situational", "medium", { mode: "behavioral", tips: "Bus factor: docs, pairing, cross-training." }),
  qx("ps040", "During an interview loop you realize the role is different than expected. What do you do?", "situational", "medium", { mode: "behavioral", tips: "Clarify role, needs, and mutual fit honestly." }),
  qx("pl001", "How do you build psychological safety on a team?", "leadership", "hard", { mode: "behavioral", tips: "Name concrete behaviors: blameless learning, turn-taking, inclusion.", roles: ["engineering-manager","project-manager","product-manager","all"] }),
  qx("pl002", "Describe your philosophy on performance management.", "leadership", "hard", { mode: "behavioral", tips: "Clarity, fairness, growth, documentation.", roles: ["engineering-manager","project-manager","product-manager","all"] }),
  qx("pl003", "How do you decide what not to do as a leader?", "leadership", "medium", { mode: "behavioral", tips: "Strategy is subtraction; criteria for no.", roles: ["engineering-manager","project-manager","product-manager","all"] }),
  qx("pl004", "Tell me how you develop high performers vs struggling performers.", "leadership", "hard", { mode: "behavioral", tips: "Differentiation without favoritism.", roles: ["engineering-manager","project-manager","product-manager","all"] }),
  qx("pl005", "How do you handle a top performer with poor teamwork?", "leadership", "hard", { mode: "behavioral", tips: "Values enforcement; skills and culture both matter.", roles: ["engineering-manager","project-manager","product-manager","all"] }),
  qx("pl006", "Describe how you run an effective 1:1.", "leadership", "easy", { mode: "behavioral", tips: "Their agenda, coaching, career, blockers.", roles: ["engineering-manager","project-manager","product-manager","all"] }),
  qx("pl007", "How do you communicate bad news to a team?", "leadership", "medium", { mode: "behavioral", tips: "Timely, honest, with agency and next steps.", roles: ["engineering-manager","project-manager","product-manager","all"] }),
  qx("pl008", "What's your approach to hiring for potential vs experience?", "leadership", "medium", { mode: "behavioral", tips: "Role needs, risk, onboarding plan.", roles: ["engineering-manager","project-manager","product-manager","all"] }),
  qx("pl009", "How do you prevent burnout on your team during peak seasons?", "leadership", "hard", { mode: "behavioral", tips: "Capacity planning, recovery, priorities.", roles: ["engineering-manager","project-manager","product-manager","all"] }),
  qx("pl010", "Describe how you create a culture of continuous feedback.", "leadership", "medium", { mode: "behavioral", tips: "Rituals, modeling, safety.", roles: ["engineering-manager","project-manager","product-manager","all"] }),
  qx("pl011", "How do you align a team around a vague company strategy?", "leadership", "hard", { mode: "behavioral", tips: "Translate strategy into local goals and narratives.", roles: ["engineering-manager","project-manager","product-manager","all"] }),
  qx("pl012", "Tell me about leading through a reorg.", "leadership", "hard", { mode: "behavioral", tips: "Empathy, clarity, stability of mission.", roles: ["engineering-manager","project-manager","product-manager","all"] }),
  qx("pl013", "How do you measure team health beyond output?", "leadership", "medium", { mode: "behavioral", tips: "Engagement, quality, learning, attrition signals.", roles: ["engineering-manager","project-manager","product-manager","all"] }),
  qx("pl014", "Describe your approach to conflict between two strong ICs.", "leadership", "hard", { mode: "behavioral", tips: "Mediate interests; set collaboration norms.", roles: ["engineering-manager","project-manager","product-manager","all"] }),
  qx("pl015", "How do you sponsor someone who isn't in the room?", "leadership", "medium", { mode: "behavioral", tips: "Visibility and opportunity, not just praise.", roles: ["engineering-manager","project-manager","product-manager","all"] }),
  qx("pl016", "What's your framework for saying no to executives?", "leadership", "hard", { mode: "behavioral", tips: "Options, risk, data, recommendation.", roles: ["engineering-manager","project-manager","product-manager","all"] }),
  qx("pl017", "How do you onboard a new manager under you?", "leadership", "medium", { mode: "behavioral", tips: "Role clarity, trust ladder, early wins.", roles: ["engineering-manager","project-manager","product-manager","all"] }),
  qx("pl018", "Describe how you handle a failed hire.", "leadership", "hard", { mode: "behavioral", tips: "Own the process; fair outcome; system fix.", roles: ["engineering-manager","project-manager","product-manager","all"] }),
  qx("pl019", "How do you balance autonomy and alignment?", "leadership", "medium", { mode: "behavioral", tips: "Guardrails, principles, inspect outcomes.", roles: ["engineering-manager","project-manager","product-manager","all"] }),
  qx("pl020", "Tell me how you keep remote or hybrid teams cohesive.", "leadership", "medium", { mode: "behavioral", tips: "Intentional rituals, async docs, inclusion.", roles: ["engineering-manager","project-manager","product-manager","all"] }),
  qx("pl021", "How do you set goals that stretch without breaking people?", "leadership", "medium", { mode: "behavioral", tips: "Challenge plus support; mid-course correction.", roles: ["engineering-manager","project-manager","product-manager","all"] }),
  qx("pl022", "Describe your decision rights model on a team.", "leadership", "easy", { mode: "behavioral", tips: "Clear owners and escalation paths.", roles: ["engineering-manager","project-manager","product-manager","all"] }),
  qx("pl023", "How do you handle credit and blame as a leader?", "leadership", "medium", { mode: "behavioral", tips: "Credit out, responsibility in, with honesty.", roles: ["engineering-manager","project-manager","product-manager","all"] }),
  qx("pl024", "What's your approach to technical debt as a manager?", "leadership", "medium", { mode: "behavioral", tips: "Portfolio risk, capacity allocation.", roles: ["engineering-manager","project-manager","product-manager","all"] }),
  qx("pl025", "How do you coach someone who is more expert than you technically?", "leadership", "hard", { mode: "behavioral", tips: "Ask powerful questions; remove blockers; career growth.", roles: ["engineering-manager","project-manager","product-manager","all"] }),
  qx("pl026", "Describe leading a team through an incident.", "leadership", "hard", { mode: "behavioral", tips: "Calm command, roles, communication, learning.", roles: ["engineering-manager","project-manager","product-manager","all"] }),
  qx("pl027", "How do you ensure diverse perspectives influence decisions?", "leadership", "medium", { mode: "behavioral", tips: "Process design, not just intent.", roles: ["engineering-manager","project-manager","product-manager","all"] }),
  qx("pl028", "Tell me how you plan succession and knowledge transfer.", "leadership", "medium", { mode: "behavioral", tips: "Bus factor and growth paths.", roles: ["engineering-manager","project-manager","product-manager","all"] }),
  qx("pl029", "How do you handle under-communication from your own manager?", "leadership", "medium", { mode: "behavioral", tips: "Manage up with structured asks.", roles: ["engineering-manager","project-manager","product-manager","all"] }),
  qx("pl030", "Describe building trust after you make a leadership mistake.", "leadership", "hard", { mode: "behavioral", tips: "Apology, repair, changed behavior.", roles: ["engineering-manager","project-manager","product-manager","all"] }),
  qx("pl031", "How do you prioritize people development against delivery pressure?", "leadership", "hard", { mode: "behavioral", tips: "Sustainable capacity is a delivery strategy.", roles: ["engineering-manager","project-manager","product-manager","all"] }),
  qx("pl032", "What's your philosophy on meetings?", "leadership", "easy", { mode: "behavioral", tips: "Purpose, agenda, outcomes, or cancel.", roles: ["engineering-manager","project-manager","product-manager","all"] }),
  qx("pl033", "How do you evaluate whether a process is helping or hurting?", "leadership", "medium", { mode: "behavioral", tips: "Friction audit and feedback.", roles: ["engineering-manager","project-manager","product-manager","all"] }),
  qx("pl034", "Describe how you handle politics without playing dirty.", "leadership", "hard", { mode: "behavioral", tips: "Transparency, coalitions around shared goals.", roles: ["engineering-manager","project-manager","product-manager","all"] }),
  qx("pl035", "How do you support someone returning from leave?", "leadership", "medium", { mode: "behavioral", tips: "Re-entry plan, reduced load, dignity.", roles: ["engineering-manager","project-manager","product-manager","all"] }),
  qx("pl036", "Tell me about creating a vision people actually remember.", "leadership", "medium", { mode: "behavioral", tips: "Simple story, repeated, tied to daily work.", roles: ["engineering-manager","project-manager","product-manager","all"] }),
  qx("pl037", "How do you decide when to step in vs let the team struggle productively?", "leadership", "hard", { mode: "behavioral", tips: "Zone of proximal development for teams.", roles: ["engineering-manager","project-manager","product-manager","all"] }),
  qx("pl038", "What's your approach to performance calibration fairness?", "leadership", "hard", { mode: "behavioral", tips: "Rubrics, bias checks, evidence.", roles: ["engineering-manager","project-manager","product-manager","all"] }),
  qx("pl039", "How do you keep high standards without fear culture?", "leadership", "medium", { mode: "behavioral", tips: "High bar plus high support.", roles: ["engineering-manager","project-manager","product-manager","all"] }),
  qx("pl040", "Describe leading without formal authority across orgs.", "leadership", "hard", { mode: "behavioral", tips: "Influence map, shared metrics, trust.", roles: ["engineering-manager","project-manager","product-manager","all"] }),
  qx("pt001", "Explain a complex system you understand well to a non-engineer.", "technical", "medium", { mode: "technical", tips: "Layered explanation; check understanding." }),
  qx("pt002", "How do you approach debugging a problem you've never seen?", "technical", "easy", { mode: "technical", tips: "Reproduce, isolate, hypothesize, verify." }),
  qx("pt003", "What's your process for code review that improves quality and culture?", "technical", "medium", { mode: "technical", tips: "Respectful, specific, teaching-oriented." }),
  qx("pt004", "How do you design APIs that age well?", "technical", "hard", { mode: "technical", tips: "Contracts, versioning, backward compatibility." }),
  qx("pt005", "Explain CAP theorem in practical terms.", "technical", "medium", { mode: "technical", tips: "Trade-offs with real examples." }),
  qx("pt006", "How do you think about caching? When does it hurt?", "technical", "medium", { mode: "technical", tips: "Invalidation, consistency, complexity cost." }),
  qx("pt007", "Describe how you'd investigate a memory leak.", "technical", "hard", { mode: "technical", tips: "Tools, profiles, ownership of allocations." }),
  qx("pt008", "What makes a good abstraction?", "technical", "hard", { mode: "technical", tips: "Stability of boundaries; leaky abstraction awareness." }),
  qx("pt009", "How do you test asynchronous or distributed behavior?", "technical", "hard", { mode: "technical", tips: "Determinism, fakes, chaos, contracts." }),
  qx("pt010", "Explain eventual consistency to a product manager.", "technical", "easy", { mode: "technical", tips: "User-visible implications." }),
  qx("pt011", "How do you choose between SQL and NoSQL?", "technical", "medium", { mode: "technical", tips: "Access patterns, consistency, ops." }),
  qx("pt012", "What's your approach to observability in a new service?", "technical", "medium", { mode: "technical", tips: "Logs, metrics, traces, SLOs." }),
  qx("pt013", "How do you handle breaking changes for clients?", "technical", "medium", { mode: "technical", tips: "Communication, migration path, dual-write if needed." }),
  qx("pt014", "Describe a performance optimization you made and how you measured it.", "technical", "medium", { mode: "technical", tips: "Baseline, change, validate." }),
  qx("pt015", "How do you secure secrets in an application?", "technical", "medium", { mode: "technical", tips: "Vaults, rotation, least privilege." }),
  qx("pt016", "What is idempotency and why does it matter?", "technical", "easy", { mode: "technical", tips: "Retries and distributed systems." }),
  qx("pt017", "How do you design for failure?", "technical", "hard", { mode: "technical", tips: "Timeouts, retries, bulkheads, fallbacks." }),
  qx("pt018", "Explain how you'd migrate a monolith module to a service.", "technical", "hard", { mode: "technical", tips: "Strangler pattern, data ownership." }),
  qx("pt019", "How do you evaluate a new framework or library?", "technical", "medium", { mode: "technical", tips: "Risk, community, fit, exit cost." }),
  qx("pt020", "What's your strategy for feature flags?", "technical", "medium", { mode: "technical", tips: "Risk control and progressive delivery." }),
  qx("pt021", "How do you ensure accessibility in UI work?", "technical", "medium", { mode: "technical", tips: "Standards, testing, inclusive design." }),
  qx("pt022", "Describe your approach to database migrations in production.", "technical", "hard", { mode: "technical", tips: "Expand/contract, zero-downtime." }),
  qx("pt023", "How do you reason about concurrency bugs?", "technical", "hard", { mode: "technical", tips: "Happens-before, races, tools." }),
  qx("pt024", "What is a good SLO vs SLA vs SLI?", "technical", "medium", { mode: "technical", tips: "Definitions and ownership." }),
  qx("pt025", "How do you prevent SQL injection and similar flaws?", "technical", "easy", { mode: "technical", tips: "Parameterized queries, validation, threat modeling." }),
  qx("pt026", "Explain pagination strategies and trade-offs.", "technical", "medium", { mode: "technical", tips: "Offset vs cursor." }),
  qx("pt027", "How do you design rate limiting?", "technical", "medium", { mode: "technical", tips: "Algorithms, fairness, multi-tenant." }),
  qx("pt028", "What's your approach to CI/CD quality gates?", "technical", "medium", { mode: "technical", tips: "Fast feedback, flaky test policy." }),
  qx("pt029", "How do you handle large file uploads?", "technical", "medium", { mode: "technical", tips: "Direct-to-storage, resumability, virus scan." }),
  qx("pt030", "Describe event-driven architecture pros and cons.", "technical", "hard", { mode: "technical", tips: "Coupling, ordering, exactly-once myths." }),
  qx("pt031", "How do you version machine learning models in production?", "technical", "hard", { mode: "technical", tips: "Reproducibility, monitoring, rollback." }),
  qx("pt032", "What makes a good dashboard for on-call?", "technical", "medium", { mode: "technical", tips: "Actionable signals, low noise." }),
  qx("pt033", "How do you approach technical documentation that people actually use?", "technical", "easy", { mode: "technical", tips: "Task-oriented docs near code." }),
  qx("pt034", "Explain OAuth at a high level for a web app.", "technical", "medium", { mode: "technical", tips: "Roles of client, auth server, resource server." }),
  qx("pt035", "How do you think about multi-tenancy isolation?", "technical", "hard", { mode: "technical", tips: "Data, performance, security boundaries." }),
  qx("pt036", "What's your approach to flaky tests?", "technical", "medium", { mode: "technical", tips: "Quarantine, fix root causes, don't ignore." }),
  qx("pt037", "How do you profile a slow web page?", "technical", "easy", { mode: "technical", tips: "Network, rendering, main thread, metrics." }),
  qx("pt038", "Describe designing a search feature end-to-end.", "technical", "hard", { mode: "technical", tips: "Indexing, ranking, relevance feedback." }),
  qx("pt039", "How do you handle data deletion requests technically?", "technical", "hard", { mode: "technical", tips: "Data map, cascading deletes, audit." }),
  qx("pt040", "What's your strategy for dependency updates and security patches?", "technical", "medium", { mode: "technical", tips: "Automation plus risk prioritization." }),
  qx("pt041", "Explain blue/green vs canary deployments.", "technical", "medium", { mode: "technical", tips: "Risk and rollback." }),
  qx("pt042", "How do you design retries without amplifying outages?", "technical", "hard", { mode: "technical", tips: "Backoff, jitter, budgets." }),
  qx("pt043", "What is a circuit breaker and when would you use one?", "technical", "medium", { mode: "technical", tips: "Failure isolation." }),
  qx("pt044", "How do you approach schema design for evolving products?", "technical", "medium", { mode: "technical", tips: "Flexibility vs integrity." }),
  qx("pt045", "Describe building an audit log that is trustworthy.", "technical", "hard", { mode: "technical", tips: "Immutability, identity, completeness." }),
  qx("pt046", "How do you debug intermittent production issues?", "technical", "hard", { mode: "technical", tips: "Telemetry, bisect, hypothesis journal." }),
  qx("pt047", "What's your philosophy on comments in code?", "technical", "easy", { mode: "technical", tips: "Why over what; keep them true." }),
  qx("pt048", "How do you ensure mobile and desktop parity thoughtfully?", "technical", "medium", { mode: "technical", tips: "Progressive enhancement, constraints." }),
  qx("pt049", "Explain the difference between authentication and authorization.", "technical", "easy", { mode: "technical", tips: "Identity vs permissions." }),
  qx("pt050", "How would you design a notification system?", "technical", "hard", { mode: "technical", tips: "Channels, preferences, reliability, spam." }),
  qx("psd001", "Design a URL shortener. What are the core components?", "system-design", "medium", { mode: "system-design", tips: "Write path, read path, collisions, scale." }),
  qx("psd002", "Design a news feed for a social app.", "system-design", "hard", { mode: "system-design", tips: "Fan-out strategies, ranking, freshness." }),
  qx("psd003", "Design a ride-sharing matching system.", "system-design", "hard", { mode: "system-design", tips: "Geo-indexing, matching latency, fairness." }),
  qx("psd004", "Design a real-time collaborative document editor.", "system-design", "hard", { mode: "system-design", tips: "CRDTs/OT, presence, conflict resolution." }),
  qx("psd005", "Design a rate limiter for a public API.", "system-design", "medium", { mode: "system-design", tips: "Algorithms, distributed counters." }),
  qx("psd006", "Design a video streaming platform at high level.", "system-design", "hard", { mode: "system-design", tips: "CDN, encoding, adaptive bitrate." }),
  qx("psd007", "Design a chat/messaging system.", "system-design", "hard", { mode: "system-design", tips: "Delivery guarantees, offline, fan-out." }),
  qx("psd008", "Design an e-commerce checkout that handles spikes.", "system-design", "hard", { mode: "system-design", tips: "Inventory consistency, payment idempotency." }),
  qx("psd009", "Design a metrics pipeline for product analytics.", "system-design", "medium", { mode: "system-design", tips: "Ingest, storage, query patterns." }),
  qx("psd010", "Design a notification fan-out for millions of users.", "system-design", "hard", { mode: "system-design", tips: "Push vs pull, batching, preferences." }),
  qx("psd011", "Design a multiplayer game session service.", "system-design", "hard", { mode: "system-design", tips: "Matchmaking, state sync, anti-cheat basics." }),
  qx("psd012", "Design a search autocomplete system.", "system-design", "medium", { mode: "system-design", tips: "Prefix indexes, ranking, latency." }),
  qx("psd013", "Design a photo sharing service.", "system-design", "medium", { mode: "system-design", tips: "Object storage, thumbnails, CDN." }),
  qx("psd014", "Design a ticket queue for IT support.", "system-design", "medium", { mode: "system-design", tips: "Priority, SLA timers, assignment rules." }),
  qx("psd015", "Design a feature flag service.", "system-design", "medium", { mode: "system-design", tips: "Config distribution, targeting, consistency." }),
  qx("psd016", "Design a job scheduler for background work.", "system-design", "hard", { mode: "system-design", tips: "Exactly-once attempts, delays, scale." }),
  qx("psd017", "Design a password reset flow securely.", "system-design", "easy", { mode: "system-design", tips: "Tokens, expiry, abuse prevention." }),
  qx("psd018", "Design a multi-tenant SaaS data model.", "system-design", "hard", { mode: "system-design", tips: "Isolation, noisy neighbor, migrations." }),
  qx("psd019", "Design an audit-compliant logging system.", "system-design", "hard", { mode: "system-design", tips: "Retention, immutability, query." }),
  qx("psd020", "Design a content moderation pipeline.", "system-design", "hard", { mode: "system-design", tips: "Human plus ML, queues, appeals, latency." }),
  qx("psd021", "Design a global session store for auth.", "system-design", "medium", { mode: "system-design", tips: "TTL, revocation, regional failover." }),
  qx("psd022", "Design a recommendation system high-level.", "system-design", "hard", { mode: "system-design", tips: "Candidates, ranking, feedback loops." }),
  qx("psd023", "Design a file sync service like Drive.", "system-design", "hard", { mode: "system-design", tips: "Conflict resolution, deltas, offline." }),
  qx("psd024", "Design an online judge / code execution sandbox.", "system-design", "hard", { mode: "system-design", tips: "Isolation, resource limits, security." }),
  qx("psd025", "Design a webhook delivery system.", "system-design", "medium", { mode: "system-design", tips: "Retries, signatures, ordering." }),
  qx("psd026", "Design a calendar availability service.", "system-design", "medium", { mode: "system-design", tips: "Time zones, concurrency, invites." }),
  qx("psd027", "Design a spam detection service for email or chat.", "system-design", "hard", { mode: "system-design", tips: "Features, false positives, feedback." }),
  qx("psd028", "Design a leaderboard for a game.", "system-design", "medium", { mode: "system-design", tips: "Ranking structures, updates, scale." }),
  qx("psd029", "Design a CI system for monorepos.", "system-design", "hard", { mode: "system-design", tips: "Caching, scheduling, isolation." }),
  qx("psd030", "Design an API gateway.", "system-design", "medium", { mode: "system-design", tips: "Auth, routing, rate limits, observability." }),
  qx("psd031", "Design a distributed lock service.", "system-design", "hard", { mode: "system-design", tips: "Correctness under partitions." }),
  qx("psd032", "Design a key-value store with TTL.", "system-design", "hard", { mode: "system-design", tips: "Storage engine, eviction, replication." }),
  qx("psd033", "Design a payment ledger.", "system-design", "hard", { mode: "system-design", tips: "Double-entry, idempotency, reconciliation." }),
  qx("psd034", "Design a location check-in system.", "system-design", "medium", { mode: "system-design", tips: "Geo queries, privacy, spam." }),
  qx("psd035", "Design an A/B experimentation platform.", "system-design", "hard", { mode: "system-design", tips: "Assignment, metrics, stats validity." }),
  qx("psd036", "Design a CDN-like cache hierarchy.", "system-design", "hard", { mode: "system-design", tips: "Invalidation, origin shield, TTLs." }),
  qx("psd037", "Design a multiplayer whiteboard.", "system-design", "hard", { mode: "system-design", tips: "Realtime sync and presence." }),
  qx("psd038", "Design an inventory system for flash sales.", "system-design", "hard", { mode: "system-design", tips: "Oversell prevention, contention." }),
  qx("psd039", "Design a secret management service.", "system-design", "hard", { mode: "system-design", tips: "Access control, rotation, audit." }),
  qx("psd040", "Design a healthcare appointment booking system.", "system-design", "medium", { mode: "system-design", tips: "Privacy, reliability, reminders." }),
  qx("pp001", "How do you decide what to build next?", "product", "medium", { mode: "behavioral", tips: "User value, business value, effort, risk.", roles: ["product-manager","product-designer","all"] }),
  qx("pp002", "Tell me about a product trade-off you made.", "product", "hard", { mode: "behavioral", tips: "Name losers and winners explicitly.", roles: ["product-manager","product-designer","all"] }),
  qx("pp003", "How would you improve our onboarding?", "product", "medium", { mode: "behavioral", tips: "Activation metric, friction audit, experiments.", roles: ["product-manager","product-designer","all"] }),
  qx("pp004", "How do you know a feature is successful?", "product", "easy", { mode: "behavioral", tips: "North star plus guardrails.", roles: ["product-manager","product-designer","all"] }),
  qx("pp005", "Design a product for job seekers practicing interviews.", "product", "medium", { mode: "behavioral", tips: "Jobs-to-be-done and loops.", roles: ["product-manager","product-designer","all"] }),
  qx("pp006", "How do you handle a CEO feature request you disagree with?", "product", "hard", { mode: "behavioral", tips: "Influence with data; escalate thoughtfully.", roles: ["product-manager","product-designer","all"] }),
  qx("pp007", "What's your approach to user research on a tight timeline?", "product", "medium", { mode: "behavioral", tips: "Lightweight methods with validity caveats.", roles: ["product-manager","product-designer","all"] }),
  qx("pp008", "How do you prioritize tech debt vs features?", "product", "hard", { mode: "behavioral", tips: "Risk and velocity framing.", roles: ["product-manager","product-designer","all"] }),
  qx("pp009", "Describe a time you killed a feature or project.", "product", "hard", { mode: "behavioral", tips: "Opportunity cost and courage.", roles: ["product-manager","product-designer","all"] }),
  qx("pp010", "How do you write a good PRD?", "product", "easy", { mode: "behavioral", tips: "Problem, users, success metrics, non-goals.", roles: ["product-manager","product-designer","all"] }),
  qx("pp011", "How would you price a freemium product?", "product", "hard", { mode: "behavioral", tips: "Willingness to pay, packaging, ethics.", roles: ["product-manager","product-designer","all"] }),
  qx("pp012", "How do you balance power users and new users?", "product", "medium", { mode: "behavioral", tips: "Segmented experiences.", roles: ["product-manager","product-designer","all"] }),
  qx("pp013", "What's your framework for roadmap communication?", "product", "medium", { mode: "behavioral", tips: "Themes over date promises.", roles: ["product-manager","product-designer","all"] }),
  qx("pp014", "How do you partner with design and engineering effectively?", "product", "medium", { mode: "behavioral", tips: "Shared goals, dual-track habits.", roles: ["product-manager","product-designer","all"] }),
  qx("pp015", "How would you reduce churn for a SaaS product?", "product", "hard", { mode: "behavioral", tips: "Diagnose cohorts; interventions.", roles: ["product-manager","product-designer","all"] }),
  qx("pp016", "Tell me how you'd launch in a new market.", "product", "hard", { mode: "behavioral", tips: "Assumptions, localization, GTM.", roles: ["product-manager","product-designer","all"] }),
  qx("pp017", "How do you handle conflicting qualitative vs quantitative data?", "product", "hard", { mode: "behavioral", tips: "Triangulation and further inquiry.", roles: ["product-manager","product-designer","all"] }),
  qx("pp018", "What's a metric you'd refuse to optimize alone?", "product", "medium", { mode: "behavioral", tips: "Goodhart's law awareness.", roles: ["product-manager","product-designer","all"] }),
  qx("pp019", "How do you scope an MVP?", "product", "easy", { mode: "behavioral", tips: "Riskiest assumptions first.", roles: ["product-manager","product-designer","all"] }),
  qx("pp020", "Describe building trust with enterprise customers.", "product", "medium", { mode: "behavioral", tips: "Reliability, support, roadmap transparency.", roles: ["product-manager","product-designer","all"] }),
  qx("pp021", "How would you improve accessibility as a product goal?", "product", "medium", { mode: "behavioral", tips: "Standards, incentives, measurement.", roles: ["product-manager","product-designer","all"] }),
  qx("pp022", "How do you run a product review meeting?", "product", "easy", { mode: "behavioral", tips: "Decisions, owners, evidence.", roles: ["product-manager","product-designer","all"] }),
  qx("pp023", "Tell me about influencing without authority as a PM.", "product", "medium", { mode: "behavioral", tips: "Narrative plus coalitions.", roles: ["product-manager","product-designer","all"] }),
  qx("pp024", "How do you evaluate build vs buy vs partner?", "product", "medium", { mode: "behavioral", tips: "Strategic control and speed.", roles: ["product-manager","product-designer","all"] }),
  qx("pp025", "How would you design notifications that don't annoy users?", "product", "medium", { mode: "behavioral", tips: "Value, control, frequency caps.", roles: ["product-manager","product-designer","all"] }),
  qx("pp026", "What's your approach to competitive analysis?", "product", "easy", { mode: "behavioral", tips: "Jobs not feature bingo.", roles: ["product-manager","product-designer","all"] }),
  qx("pp027", "How do you handle a failed experiment publicly?", "product", "medium", { mode: "behavioral", tips: "Learning culture.", roles: ["product-manager","product-designer","all"] }),
  qx("pp028", "How would you improve retention for InterviewForge?", "product", "hard", { mode: "behavioral", tips: "Habit loops, outcomes, reminders.", roles: ["product-manager","product-designer","all"] }),
  qx("pp029", "Describe stakeholder management for a cross-org initiative.", "product", "hard", { mode: "behavioral", tips: "RACI, narrative, rituals.", roles: ["product-manager","product-designer","all"] }),
  qx("pp030", "How do you incorporate ethics into product decisions?", "product", "hard", { mode: "behavioral", tips: "Harms, dual-use, mitigation.", roles: ["product-manager","product-designer","all"] }),
  qx("pp031", "How would you structure a beta program?", "product", "medium", { mode: "behavioral", tips: "Selection, feedback loops, exit criteria.", roles: ["product-manager","product-designer","all"] }),
  qx("pp032", "What's your philosophy on personalization?", "product", "medium", { mode: "behavioral", tips: "Value vs privacy vs filter bubbles.", roles: ["product-manager","product-designer","all"] }),
  qx("pp033", "How do you decide when to sunset a product?", "product", "hard", { mode: "behavioral", tips: "Costs, users, alternatives.", roles: ["product-manager","product-designer","all"] }),
  qx("pp034", "How would you measure quality of AI-generated feedback?", "product", "hard", { mode: "behavioral", tips: "Human eval, rubrics, abuse cases.", roles: ["product-manager","product-designer","all"] }),
  qx("pp035", "Tell me how you'd enter a crowded market.", "product", "hard", { mode: "behavioral", tips: "Differentiation and wedge.", roles: ["product-manager","product-designer","all"] }),
  qx("pp036", "How do you handle scope creep from sales?", "product", "medium", { mode: "behavioral", tips: "Packaging and exception process.", roles: ["product-manager","product-designer","all"] }),
  qx("pp037", "What's a product principle you operate by?", "product", "easy", { mode: "behavioral", tips: "Make it concrete with an example.", roles: ["product-manager","product-designer","all"] }),
  qx("pp038", "How do you partner with data science on experiments?", "product", "medium", { mode: "behavioral", tips: "Stats literacy and decision rules.", roles: ["product-manager","product-designer","all"] }),
  qx("pp039", "How would you design a mobile-first interview practice flow?", "product", "medium", { mode: "behavioral", tips: "Constraints and core loop.", roles: ["product-manager","product-designer","all"] }),
  qx("pp040", "Describe resolving a design-engineering impasse.", "product", "medium", { mode: "behavioral", tips: "User outcomes as tie-breaker.", roles: ["product-manager","product-designer","all"] }),
  qx("pc001", "What kind of culture helps you do your best work?", "company-culture", "easy", { mode: "company", tips: "Be specific; avoid generic platitudes." }),
  qx("pc002", "Tell me about a company value you truly live.", "company-culture", "medium", { mode: "company", tips: "Evidence over slogans." }),
  qx("pc003", "How do you handle politics in organizations?", "company-culture", "hard", { mode: "company", tips: "Integrity-preserving influence." }),
  qx("pc004", "Describe a time culture helped or hurt delivery.", "company-culture", "medium", { mode: "company", tips: "Systems, not villains." }),
  qx("pc005", "What does ownership mean to you day to day?", "company-culture", "easy", { mode: "company", tips: "Behaviors and examples." }),
  qx("pc006", "How do you contribute to inclusion beyond good intentions?", "company-culture", "medium", { mode: "company", tips: "Actions and measurement." }),
  qx("pc007", "Tell me about adapting to a culture different from your last company.", "company-culture", "medium", { mode: "company", tips: "Learning speed and authenticity." }),
  qx("pc008", "How do you give feedback upward about culture problems?", "company-culture", "hard", { mode: "company", tips: "Courage plus constructive framing." }),
  qx("pc009", "What rituals make teams healthy?", "company-culture", "easy", { mode: "company", tips: "Retros, 1:1s, recognition." }),
  qx("pc010", "Describe a time you protected team culture under pressure.", "company-culture", "hard", { mode: "company", tips: "Trade-offs with delivery." }),
  qx("pc011", "How do you respond when culture is move-fast but quality is slipping?", "company-culture", "hard", { mode: "company", tips: "Reframe speed as sustainable throughput." }),
  qx("pc012", "What does customer obsession look like in your work?", "company-culture", "medium", { mode: "company", tips: "Depth without buzzwords." }),
  qx("pc013", "How do you handle ambiguity that is cultural, not technical?", "company-culture", "medium", { mode: "company", tips: "Sense-making and norms." }),
  qx("pc014", "Tell me about earning trust in a new group.", "company-culture", "easy", { mode: "company", tips: "Small promises kept." }),
  qx("pc015", "How do you celebrate wins without creating complacency?", "company-culture", "medium", { mode: "company", tips: "Recognition plus next challenge." }),
  qx("pc016", "Describe a time you saw a toxic pattern and intervened.", "company-culture", "hard", { mode: "company", tips: "Safety and escalation." }),
  qx("pc017", "What do work-life boundaries mean in high-ambition cultures?", "company-culture", "medium", { mode: "company", tips: "Sustainable excellence." }),
  qx("pc018", "How do you onboard into unwritten rules?", "company-culture", "easy", { mode: "company", tips: "Observation and curious questions." }),
  qx("pc019", "Tell me about disagreeing with a cultural norm respectfully.", "company-culture", "hard", { mode: "company", tips: "Values plus impact." }),
  qx("pc020", "How do you build belonging on a distributed team?", "company-culture", "medium", { mode: "company", tips: "Intentional connection." }),
  qx("pc021", "What is psychological safety to you, practically?", "company-culture", "medium", { mode: "company", tips: "Mistakes, questions, dissent allowed." }),
  qx("pc022", "How do you handle hero culture that rewards burnout?", "company-culture", "hard", { mode: "company", tips: "Model and reward healthy systems." }),
  qx("pc023", "Describe aligning personal values with company mission.", "company-culture", "easy", { mode: "company", tips: "Authentic fit story." }),
  qx("pc024", "How do you respond to failure culture vs blame culture?", "company-culture", "medium", { mode: "company", tips: "Learning systems." }),
  qx("pc025", "Tell me about cross-functional culture clashes you've navigated.", "company-culture", "medium", { mode: "company", tips: "Translation between tribes." }),
  qx("pc026", "How do you keep ethics visible when incentives push otherwise?", "company-culture", "hard", { mode: "company", tips: "Speak-up design and personal courage." }),
  qx("pc027", "What does bias for action mean without recklessness?", "company-culture", "medium", { mode: "company", tips: "Reversible decisions." }),
  qx("pc028", "How do you practice humility in high-status environments?", "company-culture", "medium", { mode: "company", tips: "Credit, listening, updating." }),
  qx("pc029", "Describe a time you helped set a team norm.", "company-culture", "easy", { mode: "company", tips: "Proposal plus adoption." }),
  qx("pc030", "How do you evaluate whether a company is a healthy place to grow?", "company-culture", "medium", { mode: "company", tips: "Signals in interviews and onboarding." }),
  qx("pi001", "A user says the internet is down but only their laptop is affected. Walk through troubleshooting.", "technical", "easy", { mode: "technical", tips: "Isolate layer by layer; communicate calmly.", roles: ["it-service-desk","help-desk-analyst","desktop-support","it-support-specialist","all"] }),
  qx("pi002", "How do you prioritize tickets when everything is marked urgent?", "technical", "medium", { mode: "technical", tips: "Impact times urgency; SLA; transparent triage.", roles: ["it-service-desk","help-desk-analyst","desktop-support","it-support-specialist","all"] }),
  qx("pi003", "Describe handling a VIP user who is rude under stress.", "technical", "medium", { mode: "technical", tips: "De-escalation without sacrificing process.", roles: ["it-service-desk","help-desk-analyst","desktop-support","it-support-specialist","all"] }),
  qx("pi004", "How do you document a fix so the next agent can reuse it?", "technical", "easy", { mode: "technical", tips: "Repro steps, root cause, resolution, tags.", roles: ["it-service-desk","help-desk-analyst","desktop-support","it-support-specialist","all"] }),
  qx("pi005", "Tell me about reducing repeat tickets for the same issue.", "technical", "medium", { mode: "technical", tips: "Trend analysis and permanent fixes.", roles: ["it-service-desk","help-desk-analyst","desktop-support","it-support-specialist","all"] }),
  qx("pi006", "A security alert fires during a password reset. What do you do?", "technical", "hard", { mode: "technical", tips: "Verify identity; don't bypass security.", roles: ["it-service-desk","help-desk-analyst","desktop-support","it-support-specialist","all"] }),
  qx("pi007", "How do you explain a complex outage to non-technical users?", "technical", "easy", { mode: "technical", tips: "Clarity, ETA ranges, workarounds.", roles: ["it-service-desk","help-desk-analyst","desktop-support","it-support-specialist","all"] }),
  qx("pi008", "Describe a time you escalated correctly vs too late.", "technical", "medium", { mode: "technical", tips: "Judgment and thresholds.", roles: ["it-service-desk","help-desk-analyst","desktop-support","it-support-specialist","all"] }),
  qx("pi009", "How do you handle a ticket with incomplete information?", "technical", "easy", { mode: "technical", tips: "Structured clarifying questions.", roles: ["it-service-desk","help-desk-analyst","desktop-support","it-support-specialist","all"] }),
  qx("pi010", "Walk through resetting access for a locked-out employee securely.", "technical", "medium", { mode: "technical", tips: "Identity proofing and least privilege.", roles: ["it-service-desk","help-desk-analyst","desktop-support","it-support-specialist","all"] }),
  qx("pi011", "How do you stay current with tools while handling ticket load?", "technical", "medium", { mode: "technical", tips: "Microlearning and knowledge bases.", roles: ["it-service-desk","help-desk-analyst","desktop-support","it-support-specialist","all"] }),
  qx("pi012", "A user insists on a risky workaround. Response?", "technical", "hard", { mode: "technical", tips: "Risk communication and alternatives.", roles: ["it-service-desk","help-desk-analyst","desktop-support","it-support-specialist","all"] }),
  qx("pi013", "Describe collaborating with network or security teams during an incident.", "technical", "medium", { mode: "technical", tips: "Handoffs and shared status.", roles: ["it-service-desk","help-desk-analyst","desktop-support","it-support-specialist","all"] }),
  qx("pi014", "How do you measure your effectiveness as a support engineer?", "technical", "medium", { mode: "technical", tips: "FCR, CSAT, quality, learning.", roles: ["it-service-desk","help-desk-analyst","desktop-support","it-support-specialist","all"] }),
  qx("pi015", "Tell me about improving a runbook or knowledge article.", "technical", "easy", { mode: "technical", tips: "Before/after usability.", roles: ["it-service-desk","help-desk-analyst","desktop-support","it-support-specialist","all"] }),
  qx("pi016", "How do you handle after-hours pages and fatigue?", "technical", "medium", { mode: "technical", tips: "Handoff hygiene and health.", roles: ["it-service-desk","help-desk-analyst","desktop-support","it-support-specialist","all"] }),
  qx("pi017", "A laptop is lost with potential sensitive data. First steps?", "technical", "hard", { mode: "technical", tips: "Remote wipe, access revoke, incident process.", roles: ["it-service-desk","help-desk-analyst","desktop-support","it-support-specialist","all"] }),
  qx("pi018", "How do you coach a user who is frustrated with technology?", "technical", "easy", { mode: "technical", tips: "Patience, teach, empower.", roles: ["it-service-desk","help-desk-analyst","desktop-support","it-support-specialist","all"] }),
  qx("pi019", "Describe balancing speed of ticket closure with quality of diagnosis.", "technical", "medium", { mode: "technical", tips: "Avoid reopen rates.", roles: ["it-service-desk","help-desk-analyst","desktop-support","it-support-specialist","all"] }),
  qx("pi020", "How would you design a better service desk triage flow?", "technical", "hard", { mode: "technical", tips: "Categories, routing, self-service.", roles: ["it-service-desk","help-desk-analyst","desktop-support","it-support-specialist","all"] }),
  qx("pg001", "Tell me about a time you delivered results with incomplete requirements.", "company-culture", "hard", { mode: "company", tips: "End-to-end ownership with incomplete specs.", companyStyle: "amazon" }),
  qx("pg002", "Describe inventing a simpler solution that replaced a complex one.", "company-culture", "medium", { mode: "company", tips: "Invent and simplify with measured impact.", companyStyle: "amazon" }),
  qx("pg003", "Tell me about diving deep into a metric that didn't look right.", "company-culture", "hard", { mode: "company", tips: "Show the investigation trail.", companyStyle: "amazon" }),
  qx("pg004", "Describe earning trust when you had bad news to share.", "company-culture", "medium", { mode: "company", tips: "Honesty under pressure.", companyStyle: "amazon" }),
  qx("pg005", "Tell me about a time you insisted on the highest standards.", "company-culture", "hard", { mode: "company", tips: "Specific bar you raised and impact.", companyStyle: "amazon" }),
  qx("pg006", "Describe a time you were customer-obsessed against internal convenience.", "company-culture", "hard", { mode: "company", tips: "Customer as true north.", companyStyle: "amazon" }),
  qx("pg007", "Tell me about learning and being curious outside your role.", "company-culture", "easy", { mode: "company", tips: "Breadth with application.", companyStyle: "amazon" }),
  qx("pg008", "Describe thinking big on a small team.", "company-culture", "medium", { mode: "company", tips: "Ambition with a concrete plan.", companyStyle: "amazon" }),
  qx("pg009", "Tell me about a time you had backbone; you disagreed and committed.", "company-culture", "hard", { mode: "company", tips: "Disagree and commit example.", companyStyle: "amazon" }),
  qx("pg010", "Describe delivering on a tight deadline without sacrificing safety.", "company-culture", "medium", { mode: "company", tips: "Bias for action with guardrails.", companyStyle: "amazon" }),
  qx("pg011", "How do you structure an ambiguous problem from scratch?", "company-culture", "hard", { mode: "company", tips: "Structured problem solving.", companyStyle: "google" }),
  qx("pg012", "Explain a technical concept until I understand it; I'll ask questions.", "company-culture", "medium", { mode: "company", tips: "Communication under interactive probing.", companyStyle: "google" }),
  qx("pg013", "Tell me about improving something by an order of magnitude, not 10%.", "company-culture", "hard", { mode: "company", tips: "Impact ambition.", companyStyle: "google" }),
  qx("pg014", "Describe a time you used data to resolve a product debate.", "company-culture", "medium", { mode: "company", tips: "Analytical rigor.", companyStyle: "google" }),
  qx("pg015", "How do you handle disagreement in a design review?", "company-culture", "medium", { mode: "company", tips: "Respectful technical debate.", companyStyle: "google" }),
  qx("pg016", "Tell me about moving fast with incomplete information.", "company-culture", "hard", { mode: "company", tips: "Impact and iteration speed.", companyStyle: "meta" }),
  qx("pg017", "Describe a time you focused on long-term impact over short-term metrics.", "company-culture", "hard", { mode: "company", tips: "Impact narrative.", companyStyle: "meta" }),
  qx("pg018", "Tell me about building something that scaled to many users or teams.", "company-culture", "medium", { mode: "company", tips: "Scale mindset.", companyStyle: "meta" }),
  qx("pg019", "Describe attention to craft when nobody was watching.", "company-culture", "medium", { mode: "company", tips: "Craft standards.", companyStyle: "apple" }),
  qx("pg020", "Tell me about simplifying a user experience dramatically.", "company-culture", "medium", { mode: "company", tips: "Simplicity as hard work.", companyStyle: "apple" }),
  qx("pg021", "Describe growth mindset after critical feedback from a peer.", "company-culture", "medium", { mode: "company", tips: "Growth mindset theme.", companyStyle: "microsoft" }),
  qx("pg022", "Tell me about partnering across teams that didn't report to you.", "company-culture", "medium", { mode: "company", tips: "Cross-org collaboration.", companyStyle: "microsoft" }),
  qx("pg023", "Describe wearing multiple hats at a startup.", "company-culture", "medium", { mode: "company", tips: "Ambiguity and ownership.", companyStyle: "startup" }),
  qx("pg024", "Tell me about making a decision with almost no process in place.", "company-culture", "hard", { mode: "company", tips: "Startup judgment.", companyStyle: "startup" }),
  qx("pg025", "Describe building culture when the team was tiny.", "company-culture", "medium", { mode: "company", tips: "Early culture encoding.", companyStyle: "startup" }),
  qx("pg026", "How do you stay resilient through repeated rejection?", "company-culture", "medium", { mode: "company", tips: "Self-efficacy and recovery.", companyStyle: "general" }),
  qx("pg027", "Tell me about a time you prepared for a high-stakes evaluation.", "company-culture", "easy", { mode: "company", tips: "Metacognition and practice.", companyStyle: "general" }),
  qx("pg028", "Describe representing your values when incentives conflicted.", "company-culture", "hard", { mode: "company", tips: "Integrity under pressure.", companyStyle: "general" }),
];
